# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27f9694836d00c358b1471395c5a80cc59143b8166815adb7be74584c8b8cc94469c0619fb3f45f78c3bd914f6afd39aeb46b06251b542b9425e05c04e9c72a5

test:
  secret_key_base: 9e00f6ac676d47754f374220860124059141bc5039022704f3e7c0de24f78d7f8a402d13473cc6d608beab63932a435f922a7630f77dd2366e5d47faa58dc370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
